# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer.insurance.com:
    container_name: orderer.insurance.com
    extends:
      file: peer-base.yaml
      service: orderer-base
    volumes:
        - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
        - ../crypto-config/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/msp:/var/hyperledger/orderer/msp
        - ../crypto-config/ordererOrganizations/insurance.com/orderers/orderer.insurance.com/tls/:/var/hyperledger/orderer/tls
        - orderer.insurance.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050

  peer0.insurance.com:
    container_name: peer0.insurance.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.insurance.com
      - CORE_PEER_ADDRESS=peer0.insurance.com:7051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODEADDRESS=peer0.insurance.com:7052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.insurance.com:8051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.insurance.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.com/peers/peer0.insurance.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.com/peers/peer0.insurance.com/tls:/etc/hyperledger/fabric/tls
        - peer0.insurance.com:/var/hyperledger/production
    ports:
      - 7051:7051

  peer1.insurance.com:
    container_name: peer1.insurance.com
    extends:
      file: peer-base.yaml
      service: peer-base
environment:
      - CORE_PEER_ID=peer1.insurance.com
      - CORE_PEER_ADDRESS=peer1.insurance.com:8051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:8051
      - CORE_PEER_CHAINCODEADDRESS=peer1.insurance.com:8052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:8052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.insurance.com:8051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.insurance.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/insurance.com/peers/peer1.insurance.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/insurance.com/peers/peer1.insurance.com/tls:/etc/hyperledger/fabric/tls
        - peer1.insurance.com:/var/hyperledger/production
    ports:
      - 8051:8051

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.bank.com
      - CORE_PEER_ADDRESS=peer0.bank.com:9051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:9051
      - CORE_PEER_CHAINCODEADDRESS=peer0.bank.com:9052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:9052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.bank.com:9051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.bank.com:10051
      - CORE_PEER_LOCALMSPID=BankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank.com/peers/peer0.bank.com/tls:/etc/hyperledger/fabric/tls
        - peer0.bank.com:/var/hyperledger/production
    ports:
      - 9051:9051

  peer1.bank.com:
    container_name: peer1.bank.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.bank.com
      - CORE_PEER_ADDRESS=peer1.bank.com:10051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:10051
      - CORE_PEER_CHAINCODEADDRESS=peer1.bank.com:10052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:10052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.bank.com:10051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.bank.com:9051
      - CORE_PEER_LOCALMSPID=BankMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/bank.com/peers/peer1.bank.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/bank.com/peers/peer1.bank.com/tls:/etc/hyperledger/fabric/tls
        - peer1.bank.com:/var/hyperledger/production
    ports:
      - 10051:10051

  peer0.hospital.com:
    container_name: peer0.hospital.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.hospital.com
      - CORE_PEER_ADDRESS=peer0.hospital.com:11051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:11051
      - CORE_PEER_CHAINCODEADDRESS=peer0.hospital.com:11052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:11052
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.hospital.com:12051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hospital.com:11051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.com/peers/peer0.hospital.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.com/peers/peer0.hospital.com/tls:/etc/hyperledger/fabric/tls
        - peer0.hospital.com:/var/hyperledger/production
    ports:
      - 11051:11051

    environment:
      - CORE_PEER_ID=peer1.hospital.com
      - CORE_PEER_ADDRESS=peer1.hospital.com:12051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:12051
      - CORE_PEER_CHAINCODEADDRESS=peer1.hospital.com:12052
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:12052
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hospital.com:12051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hospital.com:11051
      - CORE_PEER_LOCALMSPID=HospitalMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/hospital.com/peers/peer1.hospital.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/hospital.com/peers/peer1.hospital.com/tls:/etc/hyperledger/fabric/tls
        - peer1.hospital.com:/var/hyperledger/production
    ports:
      - 12051:12051