# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  orderer.insurance.com:
  peer0.insurance.com:
  peer1.insurance.com:
  peer0.bank.com:
  peer1.bank.com:
  peer0.hospital.com:
  peer1.hospital.com:

networks:
  medicalinsurance:

services:

  orderer.insurance.com:
    container_name: orderer.insurance.com
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.insurance.com
    networks:
      - medicalinsurance

  peer0.insurance.com:
    container_name: peer0.insurance.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.insurance.com
    networks:
      - medicalinsurance

  peer1.insurance.com:
    container_name: peer1.insurance.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.insurance.com
    networks:
      - medicalinsurance

  peer0.bank.com:
    container_name: peer0.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.bank.com
    networks:
      - medicalinsurance

  peer1.bank.com:
    container_name: peer1.bank.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.bank.com
    networks:
      - medicalinsurance

  peer0.hospital.com:
    container_name: peer0.hospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.hospital.com
    networks:
      - medicalinsurance

  peer1.hospital.com:
    container_name: peer1.hospital.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.hospital.com
    networks:
      - medicalinsurance

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      #- FABRIC_LOGGING_SPEC=DEBUG
      - FABRIC_LOGGING_SPEC=INFO
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.insurance.com:7051
      - CORE_PEER_LOCALMSPID=InsuranceMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.com/peers/peer0.insurance.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.com/peers/peer0.insurance.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.com/peers/peer0.insurance.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/insurance.com/users/Admin@insurance.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./../chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.insurance.com
      - peer0.insurance.com
      - peer1.insurance.com
      - peer0.bank.com
      - peer1.bank.com
      - peer0.hospital.com
      - peer1.hospital.com
    networks:
      - medicalinsurance